### ISSUE TITLE
SeparatorIter should probably output final block in stream

### ISSUE THREAD

**Issue by jhugard** [green-coder/cdc-rs#6]
`SeparatorIter` currently only outputs separators that exactly match the predicate, which means the final block processed will probably not be output.

IMHO, when the source stream ends, `SeparatorIter` should output the final index value & current hash, even if it does not match the predicate.  This could potentially simplify some use cases.

**Comment by green-coder** [comment]
I am sorry, I don't plan on changing the library with a breaking change in the behavior. A separator will remain a separator and not a block-ending marker.
